---
title: "Decision_Tree"
author: "Wisdom"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Decision Tree}
set.seed(5)
library(rpart)
library(rpart.plot)
tree_model <- rpart(STATUS ~ . , data = train, method = "class")
summary(tree_model)

#plotting the tree
rpart.plot(tree_model, extra = 106)

#evaluating the model accuracy on test data
tree.pred <- predict(tree_model, test, type = "class")
x_tab <- table(Predicted = tree.pred, True = test$STATUS)
cmat <- confusionMatrix(x_tab)

```




```{r Prune Tree}

stargazer(printcp(tree_model),
          title = ("Model 1 - Cost Complexity Table"),
          type = "text",
          summary = FALSE)

plotcp(tree_model)

cp <- tree_model$cptable[which.min(tree_model$cptable[,"xerror"]), "CP"]

ptree_model <- prune(tree_model, cp)

rpart.plot(ptree_model)

ptree_pred <- predict(ptree_model, newdata = test, type = "class")

dt1_fitted <- predict(ptree_model, test, type = "prob")

dt_x_tab <- table(Predicted = ptree_pred, True = test$STATUS)

dt_cm <- confusionMatrix(x_tab)

dt_cm

#Plotting the ROC Curve

dt1_roc <- roc(test$STATUS, dt1_fitted[,1], plot = T, legacy.axes=TRUE, percent=TRUE, 
                  xlab="False Positive Percentage", ylab="True Postive Percentage", 
                  lwd=4)
par(pty = "s")
plot(dt1_roc, main = "ROC Curve Decision Tree - Model 1", col = "#4daf4a", print.auc=TRUE)

stargazer(modelmetric(dt_cm, dt1_roc),
          title = ("Model 1 Performance - Decision Tree"),
          type = "text",
          summary = FALSE)

#getting the variable importance


get_var_impt <- function(model){
    var_impt <- data.frame(model$variable.importance)
    var_impt <- rownames_to_column(var_impt, "Variable")
    var_impt <- rename(var_impt, "Gini Index" = "model.variable.importance")
    var_impt
}

var_impt <- get_var_impt(ptree_model)

var_impt %>%
    ggplot(aes(x = reorder(Variable,  - `Gini Index`), y = `Gini Index`))+
    geom_col()+
    coord_flip()+
    theme_bw()+
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())+
    labs(
        x = "variable",
        title = "Variable Importance"
    )
```


```{r Random Forest}
library(ggplot2)
library(randomForest)

rf_model <- randomForest(STATUS ~ ., data = train)

rf_model

rf_pred <- predict(rf_model, newdata = test, type = "class")

rf_fitted <- predict(rf_model, newdata = test, type = "prob")

rf_x_tab <- table(Predicted = rf_pred, True = test$STATUS)

rf_cm <- confusionMatrix(rf_x_tab)

#Plotting the ROC Curve

rf1_roc <- roc(test$STATUS, rf_fitted[,1], plot = T, legacy.axes=TRUE, percent=TRUE, 
                  xlab="False Positive Percentage", ylab="True Postive Percentage", 
                  lwd=4)
par(pty = "s")
plot(rf1_roc, main = "Model 1 - Random Forest ROC Curve", col = "#4daf4a", print.auc=TRUE)

# Getting the random Forest Metrics
rf_modelmetric <- function(CM, ROC, RF){
    accuracy = CM$overall["Accuracy"]
    precision = CM$byClass["Precision"]
    recall = CM$byClass["Recall"]
    specificity = CM$byClass["Specificity"]
    F1 = CM$byClass["F1"]
    AUC = (ROC$auc)/100
    OOB = RF$err.rate[500,1]
    perf_metric = data.frame(Score = c(accuracy, precision, recall, specificity, F1, AUC, OOB))
    row.names(perf_metric)[6:7] <- c("AUC", "OOB")
    perf_metric
}

stargazer(rf_modelmetric(rf_cm, rf1_roc, rf_model),
          title = ("Model 1 Performance - Random Forest"),
          type = "text",
          summary = FALSE,
          digits = 3)


var_impt <- get_var_impt(ptree_model)

#Identifying variable importance
rf_importance <- data.frame(rf_model$importance)
rf_importance <- rownames_to_column(rf_importance, "Variable")

rf_importance %>%
    ggplot(aes(x = reorder(Variable, -MeanDecreaseGini), y = MeanDecreaseGini))+
    geom_col()+
    theme_bw()+
    coord_flip()+
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())+
    labs(
        title = "Variable Importance",
        x = "Variable"
    )

```







