---
title: "Data_Pre-Processing"
author: "Wisdom"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Importing relevant libraries
```{r}
library(tidyverse)
library(readxl)
library(stringr)
```

Importing the data

```{r}
filepath = "C:\\Users\\User\\OneDrive\\NTU Documents\\Research Project - R Codes\\MSC Research\\KIVA_Africa.xlsx"
loan_data = read_excel(filepath)
loan_data
```

```{r}
glimpse(loan_data)
```


```{r selecting variables}
loan_data <- loan_data %>%
    select(ID, NAME, STATUS, LOAN_AMOUNT, ACTIVITY, SECTOR, COUNTRY,
           DISBURSAL_CURRENCY, CURRENCY_EXCHANGE, GENDER, REPAYMENT_INTERVAL)
```


Handling missing values
```{r handling missing values}
sapply(loan_data, function(x) sum(is.na(x)))

loan_data <- loan_data %>%
    mutate_at(c('GENDER', 'REPAYMENT_INTERVAL'), ~replace_na(., 'Unknown'))

```

Cleaning the gender column

```{r}
loan_data$GENDER[loan_data$GENDER == 0] <- "Unknown"
loan_data$GENDER[loan_data$GENDER == 'F'] <- "female"
loan_data$GENDER[loan_data$GENDER == 'M'] <- "male"
```


```{r}
count_words <- function(column, separator) {
  words <- str_split(column, separator)
  word_counts <- sapply(words, length)
  return(word_counts)
}
```

```{r}
loan_data$NUM_OWNERS <- count_words(loan_data$GENDER, ",")
```

```{r}
loan_data <- loan_data %>%
    mutate(
        GENDER = case_when(
            NUM_OWNERS > 1 ~ "Group",
            TRUE           ~ GENDER
        )
    )
    
```

```{r}
loan_data$GENDER <- str_to_title(loan_data$GENDER)
```

```{r checking for duplicates}
sum(duplicated(loan_data$ID))
```


```{r reclassify variables}
kiva_loan_data <- loan_data %>% 
    mutate(across(c(STATUS, SECTOR, ACTIVITY, COUNTRY, DISBURSAL_CURRENCY,
                    CURRENCY_EXCHANGE, GENDER, REPAYMENT_INTERVAL), factor))
```

```{r}
kiva_loan_data
```

